### ISSUE TITLE
[BUG] Py3.9 environment fails

### ISSUE THREAD

**Issue by CatEek** [CAREamics/careamics-restoration#40]
ImportError: cannot import name 'Resampling' from 'PIL.Image' after installing rich-pixels
py3.9

**Comment by jdeschamps** [comment]
I installed a new env with python 3.9 and tested the SEM notebook on the VDI. I had no problem.

I suspect your env was compromised when installing rich. The CI are also passing...

I will close this issue, reopen it if you feel that it is indeed a problem we are facing!
