### ISSUE TITLE
Add a warning for prediction w/o loading a model

### ISSUE THREAD

**Issue by CatEek** [CAREamics/careamics-restoration#55]
Trying to directly call 
`preds = engine.predict()
`
will raise
```
293     raise ValueError(
    294         "Mean or std are not specified in the configuration and in parameters"
    295     )
    297 pred_loader, stitch = self.get_predict_dataloader(
    298     external_input=external_input,
    299     mean=mean,
    300     std=std,
    301 )
    302 # TODO keep getting this ValueError: Mean or std are not specified in the
    303 # configuration and in parameters
    304 # TODO where is this error? is this linked to an issue? Mention issue here.

ValueError: Mean or std are not specified in the configuration and in parameters
```

in [https://github.com/CAREamics/careamics-restoration/blob/019c3322ea65c3ff250bd09ed61b95305eeb1a68/src/careamics_restoration/engine.py#L293](url)

Add a warning and/or restrict prediction without loading a saved model ?

**Comment by CatEek** [comment]
Another issues is that even if mean/std are provided, predict will recalculate them. This is ambiguous

**Comment by jdeschamps** [comment]
Yeah, let's add an `if trained_model` in the beginning of the function
